### ISSUE TITLE
cc is not delivered everywhere

### ISSUE THREAD

**Issue by xen0l** [nshalman/python-usdt#3]
Hi,
jcea tried to build this module on his Solaris 10 mahcines and he had troubles with it, because build_hooks.py expect cc to be found in the path. We should have a way how to bypass this, e.g. by setting CC variable. However, I am not sure what to correct convention is in Python world.

**Comment by nshalman** [comment]
Yeah, we need a C compiler to compile libusdt. I'm certainly open to suggestions, but I don't know of an easy solution...

**Comment by xen0l** [comment]
Hi,

sorry for late response, I just saw your response. Yes, looking for CC variables in environment is fine. Otherwise, I think we can default to gcc.

**Comment by nshalman** [comment]
I'll look into implementing that.
